# Prise en main du modele

In [2]:
import numpy as np 
x_train=[[0,0,0],[0,1,1]]
S=np.array(x_train)
S

array([[0, 0, 0],
       [0, 1, 1]])

In [3]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(hidden_layer_sizes=(4),activation='logistic').fit(S[:,0:2],S[:,-1])

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [4]:
clf.predict([[2,2]])

array([1])

In [5]:
clf.predict([[-1.,-2.]])

array([0])

In [6]:
np.concatenate((S,[[1,1,0]],[[1,0,1]]),axis=0)

array([[0, 0, 0],
       [0, 1, 1],
       [1, 1, 0],
       [1, 0, 1]])

In [7]:
clf.coefs_

[array([[-0.31527869,  0.12452117,  0.23165824, -0.25519885],
        [-0.02917461,  0.65878534,  0.23593908,  0.19477794]]),
 array([[ 0.4514437 ],
        [ 0.62008711],
        [ 0.08999414],
        [-0.38947077]])]

In [8]:
clf.intercepts_

[array([ 0.03291193, -0.45243318,  0.24987363,  0.12396975]),
 array([-0.28542641])]

In [9]:
X=np.array([[0,0],[1,1]])
Y=np.array([[0,1],[1,1]])

In [10]:
type(X)

numpy.ndarray

In [11]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(hidden_layer_sizes=(4))

In [12]:
from sklearn.model_selection import GridSearchCV
para = {'hidden_layer_sizes':[5,15,20,25,30]}
clf = GridSearchCV(clf, para, cv=2)
clf.fit(X,Y)
print("\n The best estimator :",clf.best_estimator_)


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multi


 The best estimator : MLPClassifier(hidden_layer_sizes=5)


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [13]:
clf = MLPClassifier(hidden_layer_sizes=(5)).fit(X,Y)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [14]:
print("\n nombre layers {}".format(clf.n_layers_))
print("\n nombre output {}".format(clf.n_outputs_)) 
print("\n fonction d'activation de  output layer {}".format(clf.out_activation_)) 
print("\n weights {}".format(clf.coefs_ )) 
print("\n bias {}".format(clf.intercepts_))  
print(" \n class labels for each output {}".format(clf.classes_))
print("\n loss {}".format(clf.loss_)) 


 nombre layers 3

 nombre output 2

 fonction d'activation de  output layer logistic

 weights [array([[ 4.02505939e-01, -6.92134927e-02,  4.88053563e-01,
         1.88085910e-01,  6.04092245e-01],
       [ 8.84653971e-01,  2.57084738e-06, -7.89274624e-01,
         2.20909880e-01,  7.62215381e-01]]), array([[ 9.19825198e-01, -1.64046130e-01],
       [ 1.08205482e-06, -5.40933805e-01],
       [-5.19960692e-01,  2.05617029e-01],
       [ 4.58191815e-01,  2.62748966e-01],
       [ 3.91899069e-01, -1.98948768e-01]])]

 bias [array([ 0.06334674, -0.73450907,  0.30110096,  0.9820541 ,  0.02975371]), array([-1.1025034,  0.4897055])]
 
 class labels for each output [0 1]

 loss 0.7676643101743743


# Travail sur le jeu de donnees Iris

In [15]:
from sklearn import svm, datasets
from sklearn.model_selection import train_test_split
iris = datasets.load_iris()  
X, y = iris.data, iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=2)

In [16]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

**Modele1**

In [17]:
import time
start_time = time.time()
clf = MLPClassifier(hidden_layer_sizes=(75),solver='adam').fit(X_train,y_train)
end_time = time.time()
print("\n Temps d'execution est:{} s".format(end_time-start_time))
print("\n  nombre d'itération est {} ".format(clf.n_iter_))
print("\n score du classifieur est {} ".format(clf.score(X_test,y_test)))


 Temps d'execution est:0.13172483444213867 s

  nombre d'itération est 200 

 score du classifieur est 1.0 


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


**Modele2**

In [18]:
start_time = time.time()
clf = MLPClassifier(hidden_layer_sizes=(75,150),solver='adam').fit(X_train,y_train)
end_time = time.time()
print("\n Temps d'execution est:{} s".format(end_time-start_time))
print("\n  nombre d'itération est {} ".format(clf.n_iter_))
print("\n score du classifieur est {} ".format(clf.score(X_test,y_test)))


 Temps d'execution est:0.4502384662628174 s

  nombre d'itération est 200 

 score du classifieur est 1.0 


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


**Modele3**

In [19]:
start_time = time.time()
clf = MLPClassifier(hidden_layer_sizes=(75,150,225),solver='adam').fit(X_train,y_train)
end_time = time.time()
print("\n Temps d'execution est:{} s".format(end_time-start_time))
print("\n  nombre d'itération est {} ".format(clf.n_iter_))
print("\n score du classifieur est {} ".format(clf.score(X_test,y_test)))


 Temps d'execution est:0.6897192001342773 s

  nombre d'itération est 161 

 score du classifieur est 1.0 


**Modele4**

In [20]:
start_time = time.time()
clf = MLPClassifier(hidden_layer_sizes=(75,150,225,275),solver='adam').fit(X_train,y_train)
end_time = time.time()
print("\n Temps d'execution est:{} s".format(end_time-start_time))
print("\n  nombre d'itération est {} ".format(clf.n_iter_))
print("\n score du classifieur est {} ".format(clf.score(X_test,y_test)))


 Temps d'execution est:1.4523088932037354 s

  nombre d'itération est 200 

 score du classifieur est 1.0 


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


**Modele5**

In [21]:
start_time = time.time()
clf = MLPClassifier(hidden_layer_sizes=(75,150,225,300),solver='adam').fit(X_train,y_train)
end_time = time.time()
print("\n Temps d'execution est:{} s".format(end_time-start_time))
print("\n  nombre d'itération est {} ".format(clf.n_iter_))
print("\n score du classifieur est {} ".format(clf.score(X_test,y_test)))


 Temps d'execution est:1.0881731510162354 s

  nombre d'itération est 146 

 score du classifieur est 0.9666666666666667 


In [22]:
from sklearn import svm
start_time = time.time()
svc = svm.SVC(kernel='poly', C=1.0).fit(X_train, y_train)
end_time = time.time()
print("\n Temps d'execution est:{} s".format(end_time-start_time))




 Temps d'execution est:0.0018486976623535156 s


In [23]:
clf.score(X_test,y_test)

0.9666666666666667

In [24]:
import numpy as np 
print("la moyenne du 1er feature(sepal length (cm)) est {} son ecart-type est {}".format(np.mean(X[0]),np.std(X[0])))
print("la moyenne du 2éme feature(sepal width (cm)) est {} son ecart-type est {}".format(np.mean(X[1]),np.std(X[1])))
print("la moyenne du 3éme feature(petal length (cm)) est {} son ecart-type est {}".format(np.mean(X[2]),np.std(X[2])))
print("la moyenne du 4éme feature(petal width (cm)) est {} son ecart-type est {}".format(np.mean(X[3]),np.std(X[3])))


la moyenne du 1er feature(sepal length (cm)) est 2.55 son ecart-type est 1.8874586088176872
la moyenne du 2éme feature(sepal width (cm)) est 2.375 son ecart-type est 1.7640507362318127
la moyenne du 3éme feature(petal length (cm)) est 2.35 son ecart-type est 1.7298843892006195
la moyenne du 4éme feature(petal width (cm)) est 2.3499999999999996 son ecart-type est 1.6560495161679194


In [25]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

## lbfgs solver

**Modele1**

In [26]:
import time
start_time = time.time()
clf = MLPClassifier(hidden_layer_sizes=(75),solver='lbfgs').fit(X_train,y_train)
end_time = time.time()
print("\n Temps d'execution est:{} s".format(end_time-start_time))
print("\n  nombre d'itération est {} ".format(clf.n_iter_))


 Temps d'execution est:0.1200096607208252 s

  nombre d'itération est 75 


In [27]:
clf.score(X_test,y_test)

0.9666666666666667

**Modele2**

In [28]:
start_time = time.time()
clf = MLPClassifier(hidden_layer_sizes=(75,150),solver='lbfgs').fit(X_train,y_train)
end_time = time.time()
print("\n Temps d'execution est:{} s".format(end_time-start_time))
print("\n  nombre d'itération est {} ".format(clf.n_iter_))


 Temps d'execution est:0.20552492141723633 s

  nombre d'itération est 47 


In [29]:
clf.score(X_test,y_test)

0.9333333333333333

**Modele3**

In [30]:
start_time = time.time()
clf = MLPClassifier(hidden_layer_sizes=(75,150,225),solver='lbfgs').fit(X_train,y_train)
end_time = time.time()
print("\n Temps d'execution est:{} s".format(end_time-start_time))
print("\n  nombre d'itération est {} ".format(clf.n_iter_))


 Temps d'execution est:0.5534505844116211 s

  nombre d'itération est 46 


In [31]:
clf.score(X_test,y_test)

0.9333333333333333

**Modele4**

In [32]:
start_time = time.time()
clf = MLPClassifier(hidden_layer_sizes=(75,150,225,275),solver='lbfgs').fit(X_train,y_train)
end_time = time.time()
print("\n Temps d'execution est:{} s".format(end_time-start_time))
print("\n  nombre d'itération est {} ".format(clf.n_iter_))


 Temps d'execution est:1.280869483947754 s

  nombre d'itération est 51 


In [33]:
clf.score(X_test,y_test)

0.9333333333333333

**Modele5**

In [34]:
start_time = time.time()
clf = MLPClassifier(hidden_layer_sizes=(75,150,225,300),solver='lbfgs').fit(X_train,y_train)
end_time = time.time()
print("\n Temps d'execution est:{} s".format(end_time-start_time))
print("\n  nombre d'itération est {} ".format(clf.n_iter_))


 Temps d'execution est:1.2618722915649414 s

  nombre d'itération est 48 


In [35]:
clf.score(X_test,y_test)

0.9666666666666667

## sgd solver

**Modele1**

In [36]:
import time
start_time = time.time()
clf = MLPClassifier(hidden_layer_sizes=(75),solver='sgd').fit(X_train,y_train)
end_time = time.time()
print("\n Temps d'execution est:{} s".format(end_time-start_time))
print("\n  nombre d'itération est {} ".format(clf.n_iter_))


 Temps d'execution est:0.16881227493286133 s

  nombre d'itération est 200 


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [37]:
clf.score(X_test,y_test)

0.8

**Modele2**

In [38]:
start_time = time.time()
clf = MLPClassifier(hidden_layer_sizes=(75,150),solver='sgd').fit(X_train,y_train)
end_time = time.time()
print("\n Temps d'execution est:{} s".format(end_time-start_time))
print("\n  nombre d'itération est {} ".format(clf.n_iter_))


 Temps d'execution est:0.37276530265808105 s

  nombre d'itération est 200 


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [39]:
clf.score(X_test,y_test)

0.9

**Modéle3**

In [40]:
start_time = time.time()
clf = MLPClassifier(hidden_layer_sizes=(75,150,225),solver='sgd').fit(X_train,y_train)
end_time = time.time()
print("\n Temps d'execution est:{} s".format(end_time-start_time))
print("\n  nombre d'itération est {} ".format(clf.n_iter_))


 Temps d'execution est:0.7998933792114258 s

  nombre d'itération est 200 


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [41]:
clf.score(X_test,y_test)

0.9

**Modele4**

In [42]:
start_time = time.time()
clf = MLPClassifier(hidden_layer_sizes=(75,150,225,275),solver='sgd').fit(X_train,y_train)
end_time = time.time()
print("\n Temps d'execution est:{} s".format(end_time-start_time))
print("\n  nombre d'itération est {} ".format(clf.n_iter_))


 Temps d'execution est:1.5054383277893066 s

  nombre d'itération est 200 


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [43]:
clf.score(X_test,y_test)

0.9

**Modele5**

In [44]:
start_time = time.time()
clf = MLPClassifier(hidden_layer_sizes=(75,150,225,300),solver='sgd').fit(X_train,y_train)
end_time = time.time()
print("\n Temps d'execution est:{} s".format(end_time-start_time))
print("\n  nombre d'itération est {} ".format(clf.n_iter_))
clf.score(X_test,y_test)


 Temps d'execution est:1.4750001430511475 s

  nombre d'itération est 200 


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


0.9

In [45]:
clf = MLPClassifier(hidden_layer_sizes=(75,150),solver='sgd')


In [46]:
from sklearn.model_selection import GridSearchCV
para = {'alpha':[0.000001,0.00001,0.001,0.01,0.0001]}
clf = GridSearchCV(clf, para, cv=3)
clf.fit(X_train,y_train)
print("\n The best estimator :",clf.best_estimator_)
print("\n the best score : ",clf.best_score_)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multi


 The best estimator : MLPClassifier(alpha=0.001, hidden_layer_sizes=(75, 150), solver='sgd')

 the best score :  0.9


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [47]:
start_time = time.time()
clf = MLPClassifier(alpha=0.000001,hidden_layer_sizes=(75,150),solver='sgd').fit(X_train,y_train)
end_time = time.time()
print("\n Temps d'execution est:{} s".format(end_time-start_time))
print("\n  nombre d'itération est {} ".format(clf.n_iter_))
clf.score(X_test,y_test)


 Temps d'execution est:0.3810129165649414 s

  nombre d'itération est 200 


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


0.9

# Travail sur le jeu de donnees MNIST


In [48]:
from sklearn.datasets import fetch_openml 
mnist = fetch_openml("mnist_784")


In [49]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(mnist.data,mnist.target,test_size=0.142)

In [50]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [51]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(hidden_layer_sizes=(75,150,225,275),solver='sgd')


In [ ]:
from sklearn.model_selection import GridSearchCV
para = {'alpha':[0.000001,0.00001,0.001,0.01,0.0001],'hidden_layer_sizes':[100,150,200,250,300,350,400,450,500]}
clf = GridSearchCV(clf, para, cv=3)
clf.fit(x_train,y_train)
print("\n The best estimator :",clf.best_estimator_)
print("\n the best score : ",clf.best_score_)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multi

In [ ]:
import time
start_time = time.time()
clf = MLPClassifier(hidden_layer_sizes=(75,150,225,275),solver='sgd').fit(X_train,y_train)
end_time = time.time()